### ISSUE TITLE
Create a Sparse Snapshot Image of a Logical Volume

### ISSUE THREAD

**Issue by victorstewart** [libyal/libvslvm#10]
Currently doing this manually via CLIs like so...

1) Create a LVM snapshot
2) copy the blocks with dd
3) concurrently compress to make file sparse

But would be fantastic to have a programmatic interface to call instead.

**Comment by joachimmetz** [comment]
@victorstewart I don't understand what you are telling/asking me in this issue. The scope of this project is to read the LVM format, if you want to do further processing with the output I recommend writing a tool that does this.

**Comment by victorstewart** [comment]
i'm saying it would be cool to have a one-shot "snapshot + compress" function in the library.

but you're saying that's too high level of a functionality to consider for the library? okay.

**Comment by joachimmetz** [comment]
This library is intended to only read LVM from user space, not to write it or create snapshots. Nothing to do with "too high level", just a different purpose. Closing issue, since question seems to be answered.
