### ISSUE TITLE
pyvslvm_test_handle.py is missing in source package

### ISSUE THREAD

**Issue by vwegert** [libyal/libvslvm#12]
Similar to [this](https://github.com/libyal/libfwnt/issues/12) and [this](https://github.com/libyal/libwrc/issues/1) issue: The file `tests/pyvslvm_test_handle.py` is present in the main Git repository, but missing in the released source packages. This causes the test to fail when run with `make check`. Manually adding the file from the master repository fixes the issue locally.

**Comment by joachimmetz** [comment]
Changes in https://github.com/libyal/libvslvm/commit/f0d0b7e2e3cc8beac400b0623188be14540b326b
