### ISSUE TITLE
I have transformed your docs into Kaitai Struct

### ISSUE THREAD

**Issue by KOLANICH** [libyal/libvslvm#4]
Thank you for the spec. I have transformed your doc into [a machine-readable description which can be compiled into parsing code](https://github.com/kaitai-io/kaitai_struct_formats/blob/master/filesystem/lvm2.ksy). Consider updating that file instead of your asciidoc in future.

**Comment by joachimmetz** [comment]
thanks for doing this but know lvm is not a file system, but a volume system. Also I need to take a closer look at Kaitai and if it can generate code I want. Seeing that structs are only one part of a parser and especially with volume management I would like control over data structure management and allocation.

> Consider updating that file instead of your asciidoc in future.

For now, I will not, the document is intended to contain notes and be human readable. I need a closer look at kaitai specification, but a first glance its nested structure does not make it easy to maintain.
