### ISSUE TITLE
Error running make

### ISSUE THREAD

**Issue by colinxy** [libyal/libvslvm#5]
I have followed the instructions to build libvslvm using GCC on mac. After configuring successfully, `make` gives me this error.

```
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../common -I../include -I../common -I../libcerror -I../libcthreads -I../libcdata -I../libclocale -I../libcnotify -I../libcsplit -I../libuna -I../libcfile -I../libcpath -I../libbfio -I../libfcache -I../libfdata -I../libfvalue -g -O2 -Wall -MT libvslvm_metadata.lo -MD -MP -MF .deps/libvslvm_metadata.Tpo -c libvslvm_metadata.c  -fno-common -DPIC -o .libs/libvslvm_metadata.o
In file included from libvslvm_metadata.c:35:
./libvslvm_libfvalue.h:35:10: fatal error: 'libfvalue_split_string.h' file not found
#include <libfvalue_split_string.h>
         ^
1 error generated.
```

**Comment by joachimmetz** [comment]
This is because the development version of libvslvm has not been updated yet to support the latest libfvalue. Unless you are actively developing libvslvm, I recommend using the source distribution package not the source from git. Also see: https://github.com/libyal/libvslvm/wiki/Building#read-first

**Comment by joachimmetz** [comment]
additional changes in https://github.com/libyal/libvslvm/commit/6919b9fc5360b79994dd2766c3d9200c9bcb8c85
