### ISSUE TITLE
LIBFVALUE_DLL_EXPORT Error

### ISSUE THREAD

**Issue by chaoticmachinery** [libyal/libvslvm#7]
Getting a LIBFVALUE_DLL_EXPORT gcc error when compiling libvslvm. I am compiling the library on a Fedora 28 64bit box. Below is the error:

make[1]: Entering directory '/root/src/libvslvm/libfvalue'
/bin/sh ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../common  -I../include -I../common -I../libcthreads -I../libcdata -I../libcnotify @LIBFVALUE_DLL_EXPORT@   -g -O2 -Wall -MT libfvalue_binary_data.lo -MD -MP -MF .deps/libfvalue_binary_data.Tpo -c -o libfvalue_binary_data.lo libfvalue_binary_data.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../common -I../include -I../common -I../libcthreads -I../libcdata -I../libcnotify @LIBFVALUE_DLL_EXPORT@ -g -O2 -Wall -MT libfvalue_binary_data.lo -MD -MP -MF .deps/libfvalue_binary_data.Tpo -c libfvalue_binary_data.c  -fPIC -DPIC -o .libs/libfvalue_binary_data.o
gcc: error: LIBFVALUE_DLL_EXPORT@: No such file or directory
make[1]: *** [Makefile:678: libfvalue_binary_data.lo] Error 1
make[1]: Leaving directory '/root/src/libvslvm/libfvalue'
make: *** [Makefile:734: all-recursive] Error 1

I am not sure why it is looking for the DLL on a Linux box.

Regards,
K Murphy

**Comment by joachimmetz** [comment]
This is a known issue. git HEAD is always work in progress and only recommended as the version to use if you are actively developing libvslvm. Also see: https://github.com/libyal/libvslvm/wiki/Building#read-first

This issue will be addressed with the next commit.
